// src/pages/ReportPage.js
import React, { useRef } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { useAdminTheme } from '../context/AdminThemeContext';
import { useAuthContext } from '../hooks/useAuthContext';
import { IoCaretBackOutline } from 'react-icons/io5';
import ReactToPrint from 'react-to-print';

const ReportPage = () => {
    const location = useLocation();
    const { user } = useAuthContext();
    const { darkMode } = useAdminTheme();
    const navigate = useNavigate();
    const componentRef = useRef();

    // Sample data
    const sampleProducts = [
        { name: 'Product A', quantitySold: 120, netSales: 2400, refunded: 50, discounts: 100, cost: 1200 },
        { name: 'Product B', quantitySold: 90, netSales: 1800, refunded: 30, discounts: 75, cost: 900 },
        { name: 'Product C', quantitySold: 60, netSales: 1200, refunded: 20, discounts: 50, cost: 600 },
        { name: 'Product D', quantitySold: 30, netSales: 600, refunded: 10, discounts: 25, cost: 300 },
    ];

    const handleBackClick = () => {
        navigate(-1); // Navigate back to the previous page
    };

    return (
        <div className={`w-full flex items-center justify-center flex-col ${darkMode ? 'bg-light-BG' : 'bg-dark-BG'}`}>
            <div className='p-4 flex flex-col items-center justify-start w-full min-h-screen'>
                <div className='flex items-center justify-between h-[8%] absolute top-0 left-0 right-0'>
                    <button
                        className={`flex gap-2 items-center py-4 px-6 outline-none ${darkMode ? 'text-light-TEXT' : 'text-dark-TEXT'}`}
                        onClick={handleBackClick}
                    >
                        <IoCaretBackOutline /> Back to Supplier List
                    </button>
                    <ReactToPrint
                        trigger={() => (
                            <button className={`py-4 px-6 ${darkMode ? 'bg-light-ACCENT' : 'bg-dark-ACCENT'}`}>
                                Print
                            </button>
                        )}
                        content={() => componentRef.current}
                        pageStyle={`@media print {
                            body {
                                font-family: Arial, sans-serif;
                                margin: 0;
                                padding: 0;
                                width: 3in; /* Set width to 3 inches */
                                overflow: hidden; /* Hide overflow content */
                            }
                            table {
                                width: 100%;
                                border-collapse: collapse;
                            }
                            th, td {
                                border: 1px solid black;
                                padding: 4px;
                                text-align: left;
                            }
                            th {
                                background-color: #f2f2f2;
                            }
                            @media print {
                                body {
                                    margin: 0;
                                    width: 3in; /* Ensure the width is 3 inches for printing */
                                }
                            }
                        `}
                    />
                </div>
                <div ref={componentRef} className={`mt-4 h-full w-full items-center flex flex-col justify-start border border-red-800 ${darkMode ? 'text-light-TEXT' : 'text-dark-TEXT'}`}>
                    <h1 className='w-full text-center text-2xl font-semibold'>SALES REPORT - APRIL 2024</h1>
                    <div className='w-full h-[30%] border'>
                        <div className=' flex my-6 border'>
                            <div className={`w-[50%] flex items-start  justify-start gap-4 border-r mr-12 ${darkMode ? 'border-light-ACCENT' : 'border-dark-ACCENT'}`}>
                                <div className='w-[40%] h-full flex flex-col gap-4'>
                                    <p>Date Generated</p>
                                    <p>Generated By</p>
                                </div>
                                <div className='w-[40%] h-full flex flex-col gap-4'>
                                    <p>Date Generated</p>
                                    <p>Generated By</p>
                                </div>
                            </div>
                            <div className={`grid grid-cols-2 gap-20 pl-6`}>
                                <div className='flex flex-col gap-4'>
                                    <p>April 2024</p>
                                    <p>April 2024</p>
                                    <p>April 2024</p>
                                    <p>April 2024</p>
                                    <p>April 2024</p>
                                </div>
                                <div className='flex flex-col gap-4'>
                                    <p>April 2024</p>
                                    <p>April 2024</p>
                                    <p>April 2024</p>
                                    <p>April 2024</p>
                                    <p>April 2024</p>
                                </div>
                            </div>
                        </div>
                        {/* Table Section */}
                        <div className='mt-12'>
                            <table className='w-full border-collapse'>
                                <thead>
                                    <tr className={`bg-${darkMode ? 'dark' : 'light'}-HEADER`}>
                                        <th className='border p-2'>Product</th>
                                        <th className='border p-2'>Quantity Sold</th>
                                        <th className='border p-2'>Net Sales (PHP)</th>
                                        <th className='border p-2'>Refunded</th>
                                        <th className='border p-2'>Discounts</th>
                                        <th className='border p-2'>Cost (PHP)</th>
                                    </tr>
                                </thead>
                                <tbody className='text-center'>
                                    {sampleProducts.map((product, index) => (
                                        <tr key={index} className={`bg-${index % 2 === 0 ? 'light' : 'dark'}-ROW`}>
                                            <td className='border p-2 text-start'>{product.name}</td>
                                            <td className='border p-2'>{product.quantitySold}</td>
                                            <td className='border p-2'>{product.netSales}</td>
                                            <td className='border p-2'>{product.refunded}</td>
                                            <td className='border p-2'>{product.discounts}</td>
                                            <td className='border p-2'>{product.cost}</td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default ReportPage;
